myuiscreen:myuiscreen.o keyboard.o xterm_control.o
	gcc myuiscreen.o keyboard.o xterm_control.o -o myuiscreen
	
myuiscreen.o:myuiscreen.c
	gcc -c myuiscreen.c
	
keyboard.o:	keyboard.c
	gcc -c keyboard.c
	
xterm_control.o:	xterm_control.c
	gcc -c xterm_control.c
	
