myuiscreen2:myuiscreen2.o keyboard.o xterm_control.o
	gcc myuiscreen2.o keyboard.o xterm_control.o -o myuiscreen2
	
myuiscreen.o:myuiscreen2.c
	gcc -c myuiscreen2.c
	
keyboard.o:	keyboard.c
	gcc -c keyboard.c
	
xterm_control.o:	xterm_control.c
	gcc -c xterm_control.c
	
